activation: softplus
angle_front: 70
angle_overhead: 30
bg_radius: -1
bitfield_warmup_iters: -1
blob_type: blob
bound: 1.0
color_lambda: 5.0
cuda_ray: true
debug: false
density_thresh: 0.1
device: cuda
dir_guidance: true
eval_freq: 10
exp_dir: ../exps/
expname: cat
fov_range: !!python/tuple
- 40
- 80
fp16: true
hidden_dim: 64
hidden_dim_bg: 64
learning_rate: 0.01
min_near: 0.1
nepochs: 100
num_heads: 4
num_layers: 3
num_layers_bg: 2
num_rays: 4096
occ_thresh: 0.001
offset:
- 0.0
- 0.0
- 0.0
preload: true
print_freq: 1
proximal_surface: 0.025
radius_range: !!python/tuple
- 1.0
- 2
render_normals: true
save_freq: 10
scale: 0.6
sil_lambda: 1.0
sketch_H: 128
sketch_W: 128
sketch_lambda: 5.0e-06
sketch_path: ../data/cat
sparsity_lambda: 0.0005
staged_rendering: true
text: a cat wearing a chef hat
train_type: rec
update_extra_interval: 16
use_2d_sketch: true
use_deepfloyd: false
use_kd_tree: false
